Speed up LESS compiling.
Appending using bash was deprecated too.

diff --git a/ubuntu-mate-welcome-dev b/ubuntu-mate-welcome-dev
--- a/ubuntu-mate-welcome-dev
+++ b/ubuntu-mate-welcome-dev
@@ -34,12 +34,13 @@ else
 
     # Compile each one and merge into one file
     touch "$dest"
-    for src in "./sources/less/"*.less;
-    do
-        lessc $src >> "$dest"
-        if [ ! -f "$dest" ]; then exit 1; fi
-    done
-    echo -e "\033[92mFinished compiling CSS.\033[0m\n"
+    lessc ./sources/boutique.less "$dest"
+    if [ $? == 0 ]; then
+        echo -e "\033[92mFinished compiling CSS.\033[0m\n"
+    else
+        echo -e "\033[91mFailed to compile CSS.\033[0m\n"
+        exit 1
+    fi
 fi
 
 # Any special operations for development
